# -*- encoding: utf-8 -*-
{
	'name': 'Account Move Sunat IT',
	'category': 'account',
	'author': 'ITGrupo',
	'depends': ['account','account_voucher','account_tables_it','account_type_doc_it'],
	'version': '1.0',
	'description':"""
	
	DOCUMENTO REGISTRADO 					DOCUMENTO QUE MODIFICA					
	TIPO DOCUMENTO: 					TIPO 					
	Nro.  COMPROBANTE: 					NUMERO					
											
	COMPROBANTE DETRACCIÓN 										
	FECHA: 					FECHA VENCIMIENTO: 					
	MONTO 										
											
	ESTOS DATOS SON DE SOLO LECTURA  Y SOLO PODRÁ SER EDITADO CUANDO EL ASIENTO CONTABLE NO ESTE RELACIONADO CON UN OBJETO ACCOUNT_INVOICE 										
	AGREGAR ESOS CAM,PO EN L ATABLA ACCOUNT_MOVE 										
											
	CREAR DOS MÓDULOS UNO QUE CREA LOS CAMPOS NECESARIOS Y OTRO QUE ES EL QUE CREA LA VISTA 										
											
	A) PARA CREAR EL REGISTRO DE COMPRAS  ES NECESARIO  AGREGAR  LA OPCION ISC Y  OTROS AL COMBOBOX TIPO DE COMPRA  QUE ESTA EN LOS CÓDIGOS DE IMPUESTOS 										
	B) CADA VEZ QUE SE REGISTRA UN ASIENTO CONTABLE EN LA COLUMNA CUENTA IMPUESTOS SE GRABA EL ID DEL IMPUESTO QUE SE ELIGIO  Y EN LA COLUMNA 										
	IMPORTE IMPUESTO BASE  SE GRABAN LOS MONTOS QUE LE CORRESPONDE A LA BASE Y AL IMPUESTO.   AHORA TANTO LA BASE COMO EL IMPUESTO ESTAN RELACIONADOS 										
	A UN CODIGO DE IMPUESTO  QUE A SU VEZ TIENE UN TIPO DE COMPRA  QUE ES LA QUE NOS VA A SERVIR PARA  SABER A QUE COLUMNA VA ESE IMPORTE;  SI TOMAMOS COMO 										
	EJEMPLO LA IMAGEN1  ADJUNTA  TENDRIAMOS LO SIGUIENTE : 										

	""",
	'auto_install': False,
	'demo': [],
	'data':	['account_move_view.xml','account_invoice_view.xml'],
	'installable': True
}
